### ISSUE TITLE
[BUG] Carry Forward on iOS Obsidian Mobile: failed to load

### ISSUE THREAD

**Issue by FelipeRearden** [jglev/obsidian-carry-forward#3]
Hello @jglev !!!!!

Little issue: every time that I open Obsidian Mobile (iOS in my case) a notification in the bottom-left corner shows that :

![2FE1F639-A1EB-4821-B046-CA5ED602D271](https://user-images.githubusercontent.com/85180696/135622301-f8efcd29-d5c7-4aa6-a330-8dea156c2525.jpeg)

And the plugin is disabled 

![0F86B642-B5F2-4CEB-B049-6DA21BF26327](https://user-images.githubusercontent.com/85180696/135622893-747c2871-0688-4859-93f0-51af12e24027.jpeg)

Version 1.1.0
Obsidian 0.12.15
MacOS and iPadOS

Just to let you know :)

Have a great day!!!

**Comment by jglev** [comment]
@FelipeRearden, thank you! I missed this when you posted it, for some reason. I've just seen it now, though!

I'm not currently seeing this issue on Android (Obsidian Android v1.0.5; Carry Forward version 1.1.0). I'm not sure what the "Version 0.0.6" message might be referring to, either -- So just to confirm, so that I can get onto the same page, do you still see this behavior when all other plugins are temporarily disabled?

**Comment by FelipeRearden** [comment]
> @FelipeRearden, thank you! I missed this when you posted it, for some reason. I've just seen it now, though!

No problem at all @jglev !!!!! :)

> I'm not currently seeing this issue on Android (Obsidian Android v1.0.5; Carry Forward version 1.1.0). 

I really don't know if is something that you could do :) 

Take a look at the release notes from version `1.0.5` for iOS. It is the same issue that I am having ...

![image](https://user-images.githubusercontent.com/85180696/147936971-14344a83-d267-4081-92c2-ef81b34273e8.jpeg)

Maybe this trigger something in your mind because Apply Patterns always worked in Mobile.

> I'm not sure what the "Version 0.0.6" message might be referring to, either

Sorry this version `0.0.6` was a result of a bad cut from the print screen. Please forget about the this version number. 

Here is a better screen shot when I try to enable the plugin on Mobile 

![image](https://user-images.githubusercontent.com/85180696/147937089-3a440fa9-be1e-4394-8341-6f90ee45045a.jpeg)


> So just to confirm, so that I can get onto the same page, do you still see this behavior when all other plugins are temporarily disabled?


Same behavior starting on mobile from an empty vault + just trying to install Carry-Forward.

---

Sorry for bring this and I am happy that is working on Android. I hope that the release notes could bring some idea related to this issue on iOS :)

Have a great day!

**Comment by FelipeRearden** [comment]
Hello @jglev !!!

Just to let you know that the same problem on iOS occurs in the Obsidian Memos plugin . The plugin developer was able to solve this issue and the plugin is running on iOS after a fix. 

This is the link for the issue : https://github.com/Quorafind/Obsidian-Memos/issues/3

This is the link of the PR that have the solution: https://github.com/Quorafind/Obsidian-Memos/pull/20

I hope this information helps you to make this amazing plugin available in iOS too 🙏 🙏 🙏 


I wish you a fantastic day!!!

**Comment by Quorafind** [comment]
For help you find bug out, here may be the error : https://github.com/jglev/obsidian-carry-forward/blob/ab334a5d9f1cb60516e5ac06a6796237d4e40193/main.ts#L44 iOS don't support lookbehind regex, which should make the iOS crashed.

**Comment by jglev** [comment]
Thank you both!

@Quorafind, do you have any more info / links that you would be willing to share about iOS not supporting lookbehind regexes? I can certainly change that line, but since the plugin allows entering whatever regex the user wants in the Settings page, I'm concerned that even if that line were changed, there could still be issues running the plugin in iOS.

Again, thank you both!

**Comment by gobbletown** [comment]
iOS Mobile still fails to load.

**Comment by jglev** [comment]
@FelipeRearden, I've just now released [`1.4.3-beta0`](https://github.com/jglev/obsidian-carry-forward/releases/tag/1.4.3-beta0). In the release, I've switched away from using a negative lookbehind regex, which hopefully will help this issue.

I don't have an iOS device, and so can't test this. Would you be willing to? And, if so, to also double-check whether the plugin seems to be working overall with this change? I would be grateful for your help!

**Comment by FelipeRearden** [comment]
> @FelipeRearden, I've just now released [`1.4.3-beta0`](https://github.com/jglev/obsidian-carry-forward/releases/tag/1.4.3-beta0). In the release, I've switched away from using a negative lookbehind regex, which hopefully will help this issue.

👀👀👀👀👀👀👀

🎉🎉🎉🎉🎉🎉🎉

> I don't have an iOS device, and so can't test this. Would you be willing to? 

YES !!!!!!!!!!!! YES !!!!!!!!!!!! YES !!!!!!!!!!!!

> And, if so, to also double-check whether the plugin seems to be working overall with this change? I would be grateful for your help!

Sure @jglev !!!! You can count on me to do the Mobile check and a overall check.

I humbly ask for 24h to achieve this. 

I will set a new vault from Mobile to do the tests and I have to figure out how to install an beta plugin form iPadOS 
- I think I already know where to start. 

Get back to you soon !

You have no idea how excited about this I am. I have been working only with Obsidian Mobile on iPadOS (with external keyboard and mouse) since the start of the year.

I miss Carry-Forward everyday 🥰

**Comment by jglev** [comment]
@FelipeRearden, thank you, for all of that! : ) And of course, take all the time you need! I appreciate your eyes on it, too!

**Comment by FelipeRearden** [comment]
Hello @jglev !!!!!!!

## 1.4.3-beta0

ℹ️ **Working absolutely PERFECT on Obsidian Mobile  1.2.3 for iPadOS 15.4**

All 12 commands were tested
Changed all Toggles from Settings
Change all text fields form settings 

We have the exact same behavior on Mobile that heavy on Desktop :)

In my opinion we are ready for the merge ✅

What a great way to start a new week. You are super @jglev :)

**Comment by FelipeRearden** [comment]
> @FelipeRearden, **thank you** for your help! You really enabled and facilitated the fix for this, and I'm grateful for your time and work.

💙💙💙💙
 
> I've just now released [`1.4.3`](https://github.com/jglev/obsidian-carry-forward/releases/tag/1.4.3). As always, please let me know as issues come up!

Amazing !!! I will let you know you I find something unusual 

I wish you a fantastic day!
