### ISSUE TITLE
The block ID generated by this plug-in is after the paragraph, not after the block. Therefore, the link cannot be used to jump to the original text. This tip is "Unable to find section #^2znmr in XXX". 

### ISSUE THREAD

**Issue by liz666** [jglev/obsidian-carry-forward#34]
The block ID generated by this plug-in is after the paragraph, not after the block. Therefore, the link cannot be used to jump to the original text. This tip is "Unable to find section #^2znmr in XXX".

**Comment by jglev** [comment]
(Closing just to direct conversation toward https://github.com/jglev/obsidian-carry-forward/discussions/35)
